apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: channelling-ingress
  namespace: channelling
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: channelling.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: channelling-php-service
                port:
                  number: 80