apiVersion: v1
kind: Secret
metadata:
  name: channelling-secret
  namespace: channelling
type: Opaque
data:
  DB_PASS: WW91clN0cm9uZ1Bhc3N3b3JkMTIzIQ==
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_PASSWORD: WW91clN0cm9uZ1Bhc3N3b3JkMTIzIQ==